version: "2"
services:
  live_ticker_bots:
    container_name: live_ticker_bots 
    image:  "live_ticker_bot"
    build: 
      context: bot
      dockerfile: live_ticker_bots.Dockerfile
    volumes:
     - ./bot:/app:z
    restart: unless-stopped
  live_ticker_optional:
    container_name: live_ticker_bots_optional 
    image:  "live_ticker_bots_optional"
    build: 
      context: bot
      dockerfile: live_ticker_bots_optional.Dockerfile
    volumes:
     - ./bot:/app:z
     - /tmp/json/:/tmp/json/
    restart: unless-stopped
