version: "3"
services:
  liveTickerBot:
    container_name: liveTickerBot 
    image:  "live_ticker_bot"
    build: 
      context: .
      dockerfile: liveTicker.Dockerfile
    volumes:
     - ./:/app:z
    restart: unless-stopped